### ISSUE TITLE
Create randomised juicypotato.exe

### ISSUE THREAD

**Issue by michaelranaldo** [ad-995/shelby#6]
Create a randomizer to pull in some static exes like juicy spuds and make them av safe.

Faff with function names is probably the simplest way rather than awakening the angry variable jobs

**Comment by mez-0** [comment]
This goes for other tools, such as mimikatz. Currently working on a module to work with the cpp files to match and replace function names dynamically.

**Comment by mez-0** [comment]
https://github.com/ad-995/shelby/commit/9971b89dddf64cdce00efdb5cb8dcc2e230a6545 addresses a solution(?) for obfuscating(?) cpp projects.
